### ISSUE TITLE
有一点小bug

### ISSUE THREAD

**Issue by nattychao** [zhengwenming/WMDragView#15]
初始化DragView给的Frame不在freeRect内，或者设置isKeepBounds，加载完成时必须要手动拖一下DragView，才能靠边或者正确显示在freeRect内，所以要重写两个方法，并主动调用一下[self keepBounds];就可以了
- (void)setFreeRect:(CGRect)freeRect {
    _freeRect = freeRect;
    [self keepBounds];
}

- (void)setIsKeepBounds:(BOOL)isKeepBounds {
    _isKeepBounds = isKeepBounds;
    [self keepBounds];
}

**Comment by zhengwenming** [comment]
已经解决。
