### ISSUE TITLE
问题：设置WMDragView按钮图片后，透明度自动变浅，图片像是加了层膜

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [zhengwenming/WMDragView#2]
[dragSwichView.button setBackgroundImage:[UIImage imageNamed:@"icon_list"] forState:0];
图片颜色和透明度自动变浅

**Comment by zhengwenming** [comment]
bug已经解决，请更新最新的代码。
原因如下
button.enable = NO;
这句代码禁止了button的交互，之后系统默认加上模糊效果，透明度变浅

我修改了
button.userInteractionEnabled = NO;
这样禁止button的交互，才不会影响button上面图片显示。


最后感谢你的issue，非常感谢；
