### ISSUE TITLE
问题：子控件WMDragView拖出父控件UIView后，还原过程中位置偏移问题

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [zhengwenming/WMDragView#3]
BUG触发流程：
1.创建控制控制器的子控件UIView，设置UIView的frame，例如：
    UIView *redView = [[UIView alloc]initWithFrame:CGRectMake(10, 40, 300, 100)];
    redView.backgroundColor = [UIColor redColor];
    [self.view addSubview:redView];

2.创建WMDragView *orangeView，使他成为redView的子控件,并在EndDragBlock设置和之前一样的frame， 例如：
   WMDragView *orangeView = [[WMDragView alloc] initWithFrame:CGRectMake(130,  30, 40, 40)];
    orangeView.backgroundColor = [UIColor orangeColor];
    [redView addSubview:orangeView];
    orangeView.EndDragBlock = ^(WMDragView *dragView){
        
        dragView.frame=CGRectMake(130,  30, 40, 40);
        
    };
3.当把orangeView拖出redView一段距离后释放手指，orangeView会向中间偏移一段距离才还原.
 请问能尽可能修复这样的位移bug吗？

**Comment by zhengwenming** [comment]
不是bug，没任何问题，是你没处理好

orangeView.EndDragBlock = ^(WMDragView *dragView) {
        [UIView animateWithDuration:0.5 animations:^{
    dragView.frame=CGRectMake(130,  30, 40, 40);
        }];
    };
加上动画就可以了。

**Comment by liunianhuaguoyanxi** [comment]
好的 谢谢
