### ISSUE TITLE
如果多个拖动按钮如何处理？

### ISSUE THREAD

**Issue by wujiegoodluck** [zhengwenming/WMDragView#5]
目前貌似互相有影响，多个的时候

**Comment by zhengwenming** [comment]
那就初始化多个啊，互不影响的，因为这个库的封装成不是单例模式。
比如三个可以拖动的按钮，你就初始化ABC三个dragView就可以了。

**Comment by zhengwenming** [comment]
已经测试，无任何影响。还望施主认真表述bug。
阿弥陀佛！
